### obtener todos los productos de la db
GET http://localhost:8080/api/products/

### obtener una cantidad determinada de productos
GET http://localhost:8080/api/products/?limite=3

### crear producto en la db - (para crear con una imagen se puede usar el formulario en views /home)
POST http://localhost:8080/api/products
Content-Type: application/json

{
    "title": "Batería JAOS 12 x 75 alta",
    "price": 280000,
    "code": "CC 75 alta",
    "description": "12x75 Tipo Edna 600",
    "status": true,
    "category": "EDNA",
    "stock": 20,
    "thumb":""
  }

### obtenemos producto con id determinado
GET  http://localhost:8080/api/products/65edce4840922c7a40fb3377

### borramos un producto
DELETE http://localhost:8080/api/products/65edcd94716a035c64244777

### modificamos un producto
PUT http://localhost:8080/api/products/65edd56d96f4bb28bba426df
Content-Type: application/json


{"price":159999}

### subimos una foto
POST http://localhost:8080/api/imagenes/65edd56d96f4bb28bba426df

### vemos los carritos
GET http://localhost:8080/api/carts/

### vemos un carrito específico
GET http://localhost:8080/api/carts/65f7976cf0591b658c609635

### creamos un carrito vacio
POST http://localhost:8080/api/carts


### agregamos un producto a un carrito determinado
POST http://localhost:8080/api/carts/65ee498a6350cf4da720e896/product/65ee79f09befe239e7aefb49

### borramos un carrito
DELETE http://localhost:8080/api/carts/65ee8867378ab40a726148c0

### ver categorías
GET http://localhost:8080/api/categories/

### agregar categoria
POST http://localhost:8080/api/categories/
Content-Type: application/json

{"cate":"Edna"}

### login
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "userName": "adminCoder@coder.com",
  "userPassword": "adminCod3r123"
}

### realizar compra
POST http://localhost:8080/api/carts/6637a7d70d36d061bcd24bc7/purchase
Content-Type: application/json
