### obtener todos los productos de la db
GET http://localhost:8080/api/products/

### obtener una cantidad determinada de productos
GET http://localhost:8080/api/products/?limite=3

### crear producto en la db - (para crear con una imagen se puede usar el formulario en views /home)
POST http://localhost:8080/api/products
Content-Type: application/json

{
    "title": "Batería Edna FW90 baja",
    "price": 280000,
    "code": "FW180",
    "description": "12x75 Tipo Edna 600",
    "status": true,
    "category": "EDNA",
    "stock": 20,
    "thumb":""
  }

### obtenemos producto con id determinado
GET  http://localhost:8080/api/products/65ec914390323f58a06c2364

### borramos un producto
DELETE http://localhost:8080/api/products/65edcd94716a035c64244777

### modificamos un producto
PUT http://localhost:8080/api/products/65edd56d96f4bb28bba426df
Content-Type: application/json

{"price":159999}

### subimos una foto
POST http://localhost:8080/api/imagenes/65edd56d96f4bb28bba426df

### vemos los carritos
GET http://localhost:8080/api/carts/

### vemos un carrito específico
GET http://localhost:8080/api/carts/65edff6d5c11886e5297583c

### creamos un carrito vacio
POST http://localhost:8080/api/carts


### agregamos un producto a un carrito determinado
POST http://localhost:8080/api/carts/65ee663dd1608b1b7c7d795f/product/65edd56d96f4bb28bba426df

### borramos un carrito
DELETE http://localhost:8080/api/carts/65ee8867378ab40a726148c0